/**
 * The landing site's CSS custom properties, generated from `theme/`.
 *
 * Before this, one site carried three hand-typed copies of the palette under
 * three sets of names: `landing/index.html` called `hairline` `--hair` and
 * `goldTintBg` `--gold-bg`, `landing/kutatas.html` called the ground `--ink`
 * and the accent `--claret`, and the template inside `scripts/render-legal.ts`
 * had a third abbreviation of its own. All three happened to hold the right
 * values, by luck rather than by construction, and nothing could have told
 * anybody when one of them stopped.
 *
 * Now there is one block, emitted from `theme/themes.ts` under the app's own
 * `--vc-*` names, so the landing site and the app cannot disagree about what
 * gold is. `scripts/render-tokens.ts` writes it into every page and
 * `scripts/landing-tokens.test.ts` fails if a committed page has fallen behind
 * it.
 *
 * ## Why a block in each page rather than one linked stylesheet
 *
 * The ground colour is on the critical path. Every rule that paints resolves
 * `var(--vc-bg)` or `var(--vc-text)`, so a stylesheet that has not arrived yet
 * paints a white page with black text — on a site whose whole register is a
 * dark stage. Inlined, the ground is in the first packet.
 *
 * The usual argument for a shared file is caching across pages, and it buys
 * almost nothing here: a visitor sees one or two of the six, and the block is
 * smaller than one of the three Google Fonts URLs the site already requests.
 */
import { tokenBlock } from "../theme/cssVars";
import { cssVarName, DEFAULT_DARK, DEFAULT_LIGHT, themes } from "../theme/themes";

/** The element the writer replaces. Anything outside it is hand-written. */
export const LANDING_TOKENS_ID = "vl-tokens";

/**
 * The page ground, one shade below the app's own.
 *
 * Deliberate, and the one place the landing site is allowed to disagree with
 * `theme/themes.ts`: the phone screenshots have to read as the lit object on a
 * dark stage, which needs the page to sit under the app rather than level with
 * it. `landing/README.md` has said so since the page was built.
 *
 * On cream it means nothing — there is no shade below paper — so in the light
 * theme the ground is simply the palette's.
 */
const INK_DARK = "#0a0507";

/** `#e4bf72` → `228,191,114`, for a canvas that varies the alpha per beam. */
function rgbTriple(hex: string): string {
  const h = hex.replace("#", "");
  const n = parseInt(h.length === 3 ? h.split("").map((c) => c + c).join("") : h, 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255].join(",");
}

const v = (token: string) => `var(${cssVarName(token)})`;

/** The generated CSS, without its `<style>` wrapper. */
export function landingTokensCss(): string {
  return [
    "/* Generated by scripts/landing-tokens.ts from theme/. Do not edit: run `npm run render:tokens`. */",

    tokenBlock(":root", DEFAULT_DARK),
    tokenBlock(':root[data-theme="light"]', DEFAULT_LIGHT),

    // The landing's own colours, each derived rather than typed.
    `:root{`,
    `/* The page ground, one shade under the app's — see landing-tokens.ts. */`,
    `--vl-ink:${INK_DARK};`,
    `/* The light rays read this as three numbers because the canvas varies the alpha per beam. */`,
    `--vl-ray-rgb:${rgbTriple(themes[DEFAULT_DARK].gold)};`,
    `/* The printed house's accent, quoted in the dark: the questionnaire's claret. */`,
    `--vl-claret:${themes[DEFAULT_LIGHT].gold};`,
    `}`,
    `:root[data-theme="light"]{--vl-ink:${v("bg")};--vl-ray-rgb:${rgbTriple(themes[DEFAULT_LIGHT].gold)}}`,

    // The base every page shares, rather than three copies of it.
    `*,*::before,*::after{box-sizing:border-box}`,
    // The app's focus ring, to the character — app/+html.tsx has the same rule.
    `:focus-visible{outline:2px solid ${v("goldTintBorder")};outline-offset:2px;border-radius:4px}`,
    // Honoured on all six pages rather than on index.html alone. A reader who
    // has asked their system for less movement should not have to ask again
    // per page.
    `@media (prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important;scroll-behavior:auto!important}}`,
  ].join("\n");
}

/** The generated CSS, wrapped in the element the writer looks for. */
export function landingTokensStyleTag(): string {
  return `<style id="${LANDING_TOKENS_ID}">\n${landingTokensCss()}\n</style>`;
}
