/**
 * Render the three legal documents as static pages of the landing site:
 * `landing/adatvedelem.html`, `landing/feltetelek.html`, `landing/impresszum.html`.
 *
 *     npm run render:legal
 *
 * `deploy:landing` runs it first, so the pages can never lag behind the text.
 *
 * The copy lives in `i18n/legal.ts`, the same module the app renders from, so
 * the app and the site publish one document rather than two that drift. Until
 * the operator details are filled in, the pages say the document is still
 * being drafted — exactly what the app's own routes say, and for the reason
 * `components/ui/LegalDocument.tsx` gives.
 *
 * Why static copies at all: while the app is in closed alpha its address is
 * not meant to be public, and the footer's legal links were the last thing on
 * the site pointing at it. Cloudflare Pages serves `adatvedelem.html` at
 * `/adatvedelem`, the same way `/kutatas` works, so the links are plain paths.
 */
import { writeFileSync } from "node:fs";

import { landingTokensStyleTag } from "./landing-tokens";
import {
  accountDeletion,
  imprint,
  legalLastUpdated,
  operator,
  operatorDetailsComplete,
  pendingNotice,
  privacyPolicy,
  termsOfService,
  type LegalDocument,
} from "../i18n/legal";

const PAGES: { slug: string; document: LegalDocument }[] = [
  { slug: "adatvedelem", document: privacyPolicy },
  { slug: "feltetelek", document: termsOfService },
  { slug: "impresszum", document: imprint },
  // Required by Google Play: a deletion route reachable without installing the app.
  { slug: "fiok-torlese", document: accountDeletion },
];

const esc = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

function body(doc: LegalDocument): string {
  if (!operatorDetailsComplete()) {
    return `<h2>${esc(pendingNotice.heading)}</h2>\n<p class="dim">${esc(pendingNotice.body)}</p>`;
  }
  const sections = doc.sections
    .map((section) => {
      const blocks = section.blocks
        .map((block) =>
          block.kind === "p"
            ? `<p class="dim">${esc(block.text)}</p>`
            : `<ul>${block.items.map((item) => `<li>${esc(item)}</li>`).join("")}</ul>`
        )
        .join("\n");
      return `<section>\n<h2>${esc(section.heading)}</h2>\n${blocks}\n</section>`;
    })
    .join("\n");
  return `<p class="lead">${esc(doc.lead)}</p>\n${sections}\n<p class="faint">Utoljára frissítve: ${esc(legalLastUpdated)}</p>`;
}

function page(slug: string, doc: LegalDocument): string {
  return `<!doctype html>
<!-- Generated by scripts/render-legal.ts. Do not edit this file: the text
     lives in i18n/legal.ts and the template in that script, and the next
     \`npm run render:legal\` will overwrite anything typed here. -->
<html lang="hu">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#0a0507">
<title>${esc(doc.title)} · Vastaps</title>
<link rel="canonical" href="https://vastaps.app/${slug}">
<link rel="icon" href="/icon.svg" type="image/svg+xml">
<link rel="icon" href="/favicon.png" sizes="32x32" type="image/png">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Bodoni+Moda:opsz,wght@6..96,400;6..96,500;6..96,600&family=Sora:wght@300;400;500;600&display=swap">
${landingTokensStyleTag()}
<style>
/* Generated by scripts/render-legal.ts — edit the text in i18n/legal.ts, not here.
   The palette, the box model, the focus ring and the reduced-motion rule are
   the generated block above, shared with index.html and the questionnaire.
   What is left here is the two colours the palette has no name for and the
   one that is nearly its hairline — .10 where the app's is .11. */
:root {
}
body { margin: 0; background: var(--vl-ink); color: var(--vc-text); font-family: var(--vl-sans); font-size: var(--vl-size-copy); line-height: var(--vl-leading-copy); -webkit-font-smoothing: antialiased; min-height: 100svh; display: flex; flex-direction: column; }
.shell { width: min(100% - 2 * var(--vl-gutter), 66ch); margin-inline: auto; }
.nav { border-bottom: 1px solid var(--vc-hairline); }
.nav__in { display: flex; align-items: center; height: 64px; }
.brand { display: flex; align-items: center; gap: var(--vl-space-sm); text-decoration: none; color: inherit; }
.brand__mark { width: 26px; height: 26px; color: var(--vc-gold); }
.brand__name { font-family: var(--vl-display); font-size: var(--vl-size-heading); font-weight: var(--vl-weight-semibold); }
main { flex: 1; padding-block: clamp(var(--vl-space-3xl), 5vw, var(--vl-space-5xl)) clamp(var(--vl-space-4xl), 6vw, var(--vl-space-5xl)); }
h1, h2 { font-family: var(--vl-display); font-weight: var(--vl-weight-semibold); line-height: var(--vl-leading-marquee); letter-spacing: var(--vl-tracking-display); margin: 0; text-wrap: balance; }
h1 { font-size: var(--vl-size-act); margin-bottom: var(--vl-space-lg); }
h2 { font-size: var(--vl-size-title); margin-top: var(--vl-space-3xl); margin-bottom: var(--vl-space-sm); }
section + section h2 { margin-top: var(--vl-space-3xl); }
p { margin: 0 0 var(--vl-space-lg); }
.lead { color: var(--vc-text-dim); font-size: var(--vl-size-lede); font-weight: var(--vl-weight-regular); }
.dim { color: var(--vc-text-dim); }
.faint { color: var(--vc-text-faint); font-size: var(--vl-size-bodySmall); margin-top: var(--vl-space-4xl); }
ul { margin: 0 0 var(--vl-space-lg); padding-left: var(--vl-space-xl); color: var(--vc-text-dim); }
li { margin-bottom: var(--vl-space-xs); }
a { color: var(--vc-gold); text-decoration: none; border-bottom: 1px solid var(--vc-gold-tint-border); }
a:hover { color: var(--vl-gold-lift); }
.foot { border-top: 1px solid var(--vc-hairline); padding-block: var(--vl-space-2xl); font-size: var(--vl-size-bodySmall); color: var(--vc-text-faint); }
.foot__in { display: flex; flex-wrap: wrap; gap: var(--vl-space-sm) var(--vl-space-2xl); justify-content: space-between; }
.foot a { color: var(--vc-text-dim); border: 0; }
.foot a:hover { color: var(--vc-text); }
</style>
</head>
<body>
<header class="nav">
  <div class="shell nav__in">
    <a class="brand" href="/" aria-label="Vastaps — vissza a főoldalra">
      <svg class="brand__mark" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M4 5c2.6 1.6 5.3 2.4 8 2.4S17.4 6.6 20 5v8.2c0 3.7-3.6 6.8-8 6.8s-8-3.1-8-6.8V5Z" fill="none" stroke="currentColor" stroke-width="1.6"/></svg>
      <span class="brand__name">Vastaps</span>
    </a>
  </div>
</header>
<main>
  <article class="shell">
    <h1>${esc(doc.title)}</h1>
${body(doc)}
  </article>
</main>
<footer class="foot">
  <div class="shell foot__in">
    <p>Vastaps — magyar színházi napló.</p>
    <p><a href="/impresszum">Impresszum</a> &nbsp;·&nbsp; <a href="/adatvedelem">Adatvédelem</a> &nbsp;·&nbsp; <a href="/feltetelek">Feltételek</a> &nbsp;·&nbsp; <a href="mailto:${operator.email}?subject=Vastaps">Kapcsolat</a></p>
  </div>
</footer>
</body>
</html>
`;
}

for (const { slug, document } of PAGES) {
  writeFileSync(`landing/${slug}.html`, page(slug, document));
  console.log(`wrote landing/${slug}.html${operatorDetailsComplete() ? "" : " (pending notice: operator details not filled in)"}`);
}
